name: Build Raspberry Pi OS Image (pi-gen)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your fork
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y git quilt parted realpath qemu-user-static debootstrap zerofree \
            pxz zip dosfstools bsdtar libcap2-bin grep rsync xz-utils bc \
            coreutils systemd-container pigz

      - name: Build image
        run: |
          sudo ./build.sh

      - name: Archive image
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: pi-gen-image
          path: deploy/